// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yotunjzgomkuuwpyftqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvdHVuanpnb21rdXV3cHlmdHFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0Mjk4NTMsImV4cCI6MjA2NjAwNTg1M30.bFCR2HIpdG_4L_ZCuojseZfqbMHaLAco3SFdPqDKkqU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);